f = open("WissamXpoHub_V3_Frontend_FIXED.html", encoding="utf-8")
html = f.read()
f.close()
idx = html.find("checkExistingSession")
fn_start = html.find("{", idx)
print(repr(html[fn_start:fn_start+300]))
